datasets:
  laionmulti:
    data_type: images
    build_info:
      storage: /ibex/project/c2133/blip_dataset/laion2B_multi/laion2b_multi/{00000..02546}.tar
      # storage: /ibex/project/c2133/blip_dataset/laion_1b/laion_gpu/{00000..10488}.tar