model:
  arch: mini_gpt4

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True
  freeze_qformer: True
  model_type: "vit_h"
  device: "cuda"
  segment_checkpoint: "/ibex/project/c2133/segment_ckpt/sam_vit_h_4b8939.pth"

  # Q-Former
  num_query_token: 32

  # Vicuna
  # llama_model: "/ibex/project/c2133/vicuna"
  # llama_model: "/ibex/user/mohameys/llm/mt0/models--bigscience--mt0-xxl-mt/snapshots/5fd24a466bb6b26ff9c60ec13ea09f74226aaade/"
  llama_model: "/ibex/user/mohameys/llm/mt0/bloomz-7b1-mt"

  # generation configs
  prompt: ""

  # use_artelingo: True

preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip2_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
